class CreateWdwSourcesTouringplansDiningVenues < ActiveRecord::Migration[6.1]
  def change
    create_table :wdw_sources_touringplans_dining_venues do |t|
    t.string "name"
    t.string "short_name"
    t.string "permalink"
    t.string "venue_permalink"
    t.integer "land_id"
    t.string "category_code"
    t.string "portion_size"
    t.string "cost_code"
    t.string "cuisine"
    t.string "phone_number"
    t.string "entree_range"
    t.string "when_to_go"
    t.string "parking"
    t.string "bar"
    t.string "wine_list"
    t.string "dress"
    t.string "awards"
    t.string "lunch_hours"
    t.string "dinner_hours"
    t.string "selection"
    t.string "setting_atmosphere"
    t.string "other_recommendations"
    t.string "summary"
    t.string "house_specialties"
    t.string "counter_quality_rating"
    t.string "counter_value_rating"
    t.string "table_quality_rating"
    t.string "table_value_rating"
    t.string "overall_rating"
    t.string "service_rating"
    t.string "friendliness_rating"
    t.string "adult_breakfast_menu_url"
    t.string "adult_lunch_menu_url"
    t.string "adult_dinner_menu_url"
    t.string "child_breakfast_menu_url"
    t.string "child_lunch_menu_url"
    t.string "child_dinner_menu_url"
    t.boolean "requires_credit_card"
    t.boolean "requires_pre_payment"
    t.integer "plan_x_coord"
    t.integer "plan_y_coord"
    t.integer "old_park_id"
    t.integer "old_attraction_id"
    t.string "plan_name"
    t.datetime "extinct_on"
    t.datetime "opened_on"
    t.string "disney_permalink"
    t.string "code"
    t.boolean "accepts_reservations"
    t.boolean "kosher_available"
    t.integer "dinable_id"
    t.string "dinable_type"
    t.string "breakfast_hours"
    t.integer "operator_id"
    t.string "operator_url"
    t.string "operator_type"
    t.integer "walking_time_proxy_id"
    t.string "sort_name"
    t.boolean "mobile_ordering"
    t.string "extinct_on_uncertain"
    t.string "opened_on_uncertain"
    t.string "opened_on_known"
    t.text "operational_notes"
    t.string "latitude"
    t.string "longitude"
    t.string "summary_at_top"

    t.timestamps
    end
  end
end
